export const list = {
    bangla_new: [
        "Asadoma_Sadgamayo.m4a",
        "ke-tui-bol.mp3",
        "mon-majhi-re.mp3",
        "bojhena-se-bojhena.mp3",
    ],
    bangla_retro: [
        "chanchal-mon-anmona-hoi.mp3",
        "aaj-noi-gun-gun-gunjan-prem-e.mp3",
        "gram-chhara-oi-ranga-matir-path.mp3",
        "Hoyto_Tomari_Jannya_Manna_Dey.m4a",
        "aguner-poroshmoni.mp3",
    ],
    classical: [
        "Ludwig_Van_Beethoven_Symphony_No_5_Op_67_Classic_Flames.mp3",
        "alla-turka-slowed.mp3",
        "24-caprices.mp3",
        "fur-elise-beethoven.mp3",
        "Goetia.mp3",
        "Moonlight-Sonata-Ludwig-van-Beethoven.mp3",
        "alla-turka-mozrat.mp3",
        "lacrimosa-mozrat.mp3",
        "paganini-caprice-no-5.mp3",
        "fur-elise-slowed.mp3",
    ],
    hindi_new: [
        "Raabta_Kehte_Hain_Khuda_Ne.mp3",
        "Agar_Tum_Mil_Jao.mp3",
        "luka-chhupi.mp3",
        "AAP_KI_NAZRON_NE_SAMJHA_SANAM.mp3",
        "Yeh_Raat_Bheegi_Bheegi.mp3",
        "Yeh_Raaten_Yeh_Mausam_Kishore_Kumar_Asha_Bhosle_Sanam_Simra.mp3",
    ],
    hindi_retro: [
        "Mera_Dil_Ye_Pukare_Aaja_Vaijayanti_Mala_Lata_Mangeshkar.mp3",
        "gun-guna-rahe-hai-vramar.mp3",
        "Lag_Ja_Gale_Se_Phir_Lata_Mangeshkar.mp3",
        "mere-mehboob-qyamat-hogi-kishore-kumar.mp3",
        "dilbar-mere-kabtak-mujhe.mp3",
        "Jeena_Yahan_Marna_Yahan_From_Mera_Naam_Joker.m4a",
    ],
    miscellaneous: [
        "galliya.mp3",
        "agnipath.mp3",
        "light-no-theme.mp3",
        "classic1.mp3",
    ],
    nature: [
        "sea_beach.mp3",
        "pastoral.mp3",
        "rain.mp3",
        "chime.mp3",
        "deep_forest.mp3",
    ],
    rabindra_sangeet: [
        "Ore_Grihobasi.m4a",
        "purano-sei-diner-kotha-hemanta-mukherjee.mp3",
        "majhe-majhe-tobo-dekha-pai-chirodin-keno-pai-na.mp3",
        "Amar_Sonar_Horin_Chai_-_Arijit_Chakraborty.m4a",
        "Ekla_Cholo_Re_Anupom_Roy.m4a",
        "amaro-parano-jaha-chay.m4a",
        "Tomay_Hrid_Majhare_Rakhbo_-_Borno_Chakroborty.m4a",
        "Premero_Joare_Bhasabe_-_Dwijen_Mukherjee.m4a",
        "ami-chini-go-chini-tomare-ogo-bidesini.m4a",
    ],
    religious: [
        "hari_haraye_namo_krishna_jadhav_bhai_namo.mp3",
        "ek-radha-ek-mira.mp3",
        "Achyutam_Keshavam_by_Alka_Yagnik_From_Achyuta.m4a",
    ],
};
